name: Deploy BitByBit API

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BITBYBITAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITBYBITAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITBYBITAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR
        run: |
          docker build -t bitbybit.azurecr.io/bitbybit-api:${{ github.sha }} .
          docker push bitbybit.azurecr.io/bitbybit-api:${{ github.sha }}

      - name: Deploy to Container App using managed identity
        run: |
          az containerapp update \
            --name bitbybit-api \
            --resource-group pythonapi \
            --image bitbybit.azurecr.io/bitbybit-api:${{ github.sha }}
