name: Trigger auto deployment for bitbybit-api

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/bitbybit-api-AutoDeployTrigger-c1d72aaf-7816-4ee8-be97-ec9acec6533e.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BITBYBITAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITBYBITAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITBYBITAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image
        run: |
          docker build -t bitbybit.azurecr.io/bitbybit-api:${{ github.sha }} .
          echo "${{ secrets.BITBYBITAPI_REGISTRY_PASSWORD }}" | docker login bitbybit.azurecr.io -u ${{ secrets.BITBYBITAPI_REGISTRY_USERNAME }} --password-stdin
          docker push bitbybit.azurecr.io/bitbybit-api:${{ github.sha }}

      - name: Deploy manually with registry creds
        run: |
          az containerapp update \
            --name bitbybit-api \
            --resource-group pythonapi \
            --image bitbybit.azurecr.io/bitbybit-api:${{ github.sha }} \
            --registry-server bitbybit.azurecr.io \
            --registry-username ${{ secrets.BITBYBITAPI_REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.BITBYBITAPI_REGISTRY_PASSWORD }}
