name: Trigger auto deployment for bitbybit-trashapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/bitbybit-trashapi-AutoDeployTrigger-fb2d958a-5beb-4234-b773-b7151bebe45c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BITBYBITTRASHAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BITBYBITTRASHAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BITBYBITTRASHAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bitbybittrash.azurecr.io
          registryUsername: ${{ secrets.BITBYBITTRASHAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BITBYBITTRASHAPI_REGISTRY_PASSWORD }}
          containerAppName: bitbybit-trashapi
          resourceGroup: BitByBitTrashB_group
          imageToBuild: bitbybittrash.azurecr.io/bitbybit-trashapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

